-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 13:48:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stud_v23_she199
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stud_v23_she199
-- -----------------------------------------------------
USE `stud_v23_she199` ;

-- -----------------------------------------------------
-- Table `stud_v23_she199`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`user` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(100) NULL,
  `admin` TINYINT NOT NULL,
  `password` VARCHAR(118) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`country` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`language` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `flag` VARCHAR(100) NOT NULL,
  `default` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`country_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`country_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`country_meta` (
  `country_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`, `language_id`),
  INDEX `cm_country_id_fk_idx` (`country_id` ASC) VISIBLE,
  INDEX `cm_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `cm_country_id_fk`
    FOREIGN KEY (`country_id`)
    REFERENCES `stud_v23_she199`.`country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cm_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`city` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `c_country_id_fk_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `c_country_id_fk`
    FOREIGN KEY (`country_id`)
    REFERENCES `stud_v23_she199`.`country` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`city_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`city_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`city_meta` (
  `city_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  INDEX `ctm_city_id_fk_idx` (`city_id` ASC) VISIBLE,
  INDEX `ctm_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  PRIMARY KEY (`city_id`, `language_id`),
  CONSTRAINT `ctm_city_id_fk`
    FOREIGN KEY (`city_id`)
    REFERENCES `stud_v23_she199`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ctm_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_type` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `points` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`achievement` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`achievement` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `icon` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_type_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_type_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_type_meta` (
  `sight_type_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(2000) NULL,
  INDEX `stm_sight_type_id_idx` (`sight_type_id` ASC) VISIBLE,
  INDEX `stm_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  PRIMARY KEY (`sight_type_id`, `language_id`),
  CONSTRAINT `stm_sight_type_id_fk`
    FOREIGN KEY (`sight_type_id`)
    REFERENCES `stud_v23_she199`.`sight_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stm_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`achievement_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`achievement_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`achievement_meta` (
  `achievement_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(2000) NULL,
  INDEX `am_achievement_id_fk_idx` (`achievement_id` ASC) VISIBLE,
  INDEX `am_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  PRIMARY KEY (`achievement_id`, `language_id`),
  CONSTRAINT `am_achievement_id_fk`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `stud_v23_she199`.`achievement` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `am_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`age_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`age_category` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`age_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `min_age` INT UNSIGNED NULL,
  `max_age` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`page_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`page_element` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`page_element` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `system_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`page_element_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`page_element_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`page_element_meta` (
  `page_element_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `text` TEXT(3000) NOT NULL,
  PRIMARY KEY (`page_element_id`, `language_id`),
  INDEX `pem_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `pem_page_element_id_fk`
    FOREIGN KEY (`page_element_id`)
    REFERENCES `stud_v23_she199`.`page_element` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pem_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`friend` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`friend` (
  `follower` INT UNSIGNED NOT NULL,
  `following` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`follower`, `following`),
  INDEX `f_following_fk_idx` (`following` ASC) VISIBLE,
  CONSTRAINT `f_follower_kf`
    FOREIGN KEY (`follower`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `f_following_fk`
    FOREIGN KEY (`following`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_id` INT UNSIGNED NOT NULL,
  `age_category_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `active` TINYINT NOT NULL,
  `open_time` TIME NULL,
  `close_time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `s_age_category_id_fk_idx` (`age_category_id` ASC) VISIBLE,
  INDEX `s_city_id_fk_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `s_age_category_id_fk`
    FOREIGN KEY (`age_category_id`)
    REFERENCES `stud_v23_she199`.`age_category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `s_city_id_fk`
    FOREIGN KEY (`city_id`)
    REFERENCES `stud_v23_she199`.`city` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_meta` (
  `sight_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(3000) NULL,
  PRIMARY KEY (`sight_id`, `language_id`),
  INDEX `sm_language_id_fk_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `sm_sight_id_fk`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sm_language_id_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_has_achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_has_achievement` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_has_achievement` (
  `achievement_id` INT UNSIGNED NOT NULL,
  `sight_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`achievement_id`, `sight_id`),
  INDEX `ast_sight_id_fk_idx` (`sight_id` ASC) VISIBLE,
  CONSTRAINT `ast_achievement_id_fk`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `stud_v23_she199`.`achievement` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ast_sight_id_fk`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_has_sight_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_has_sight_type` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_has_sight_type` (
  `sight_id` INT UNSIGNED NOT NULL,
  `sight_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sight_type_id`, `sight_id`),
  INDEX `sst_sight_id_idx` (`sight_id` ASC) VISIBLE,
  CONSTRAINT `sst_sight_id_fk`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sst_sight_type_id_fk`
    FOREIGN KEY (`sight_type_id`)
    REFERENCES `stud_v23_she199`.`sight_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`group` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(3000) NULL,
  `avatar` VARCHAR(100) NULL,
  `open` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`user_in_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`user_in_group` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`user_in_group` (
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  `leader` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `ug_group_id_fk_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `ug_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ug_group_id_fk`
    FOREIGN KEY (`group_id`)
    REFERENCES `stud_v23_she199`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`wishlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `group_id` INT UNSIGNED NULL,
  `sight_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wl_user_id_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `wl_group_id_fk_idx` (`group_id` ASC) VISIBLE,
  INDEX `wl_sight_id_fk_idx` (`sight_id` ASC) VISIBLE,
  CONSTRAINT `wl_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `wl_group_id_fk`
    FOREIGN KEY (`group_id`)
    REFERENCES `stud_v23_she199`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `wl_sight_id_fk`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`visited_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`visited_list` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`visited_list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `group_id` INT UNSIGNED NULL,
  `sight_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vl_user_id_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `vl_group_id_fk_idx` (`group_id` ASC) VISIBLE,
  INDEX `vl_sight_id_fk_idx` (`sight_id` ASC) VISIBLE,
  CONSTRAINT `vl_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vl_group_id_fk`
    FOREIGN KEY (`group_id`)
    REFERENCES `stud_v23_she199`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vl_sight_id_fk`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`user_system_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`user_system_meta` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`user_system_meta` (
  `user_id` INT UNSIGNED NOT NULL,
  `verified` TINYINT NOT NULL,
  `open_profile` TINYINT NOT NULL,
  `show_real_name` TINYINT NOT NULL,
  `show_friend_list` TINYINT NOT NULL,
  `current_language` INT UNSIGNED NULL,
  `current_city` INT UNSIGNED NULL,
  PRIMARY KEY (`user_id`),
  INDEX `um_current_language_fk_idx` (`current_language` ASC) VISIBLE,
  INDEX `um_current_city_fk_idx` (`current_city` ASC) VISIBLE,
  CONSTRAINT `um_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `um_current_language_fk`
    FOREIGN KEY (`current_language`)
    REFERENCES `stud_v23_she199`.`language` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `um_current_city_fk`
    FOREIGN KEY (`current_city`)
    REFERENCES `stud_v23_she199`.`city` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`verification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`verification` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`verification` (
  `user_id` INT UNSIGNED NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `v_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`password_recovery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`password_recovery` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`password_recovery` (
  `user_id` INT UNSIGNED NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `pw_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `stud_v23_she199`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_she199`.`sight_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_she199`.`sight_photo` ;

CREATE TABLE IF NOT EXISTS `stud_v23_she199`.`sight_photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sight_id` INT UNSIGNED NOT NULL,
  `photo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sf_sight_id_idx` (`sight_id` ASC) VISIBLE,
  CONSTRAINT `sf_sight_id`
    FOREIGN KEY (`sight_id`)
    REFERENCES `stud_v23_she199`.`sight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
